version: "3.2"
services:  
    streamlit:
        build: streamlit
        ports:
           - "8501:8501"   
        networks:
           node_net:
             ipv4_address: 172.28.1.5
    fastapi:
        build: fastapi
        ports:
           - "8001:8001"   
        networks:
           node_net:
             ipv4_address: 172.28.1.6     
    database:
        build: data
        ports:
           - "5432:5432"  
        networks:
           node_net:
             ipv4_address: 172.28.1.7
        volumes:
           - database-data:/var/lib/postgresql/data
        env_file:
           - ./data/database.env

volumes:
    database-data:

networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16